name: Publish Go Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  

      - name: Build and Test
        run: |
          go mod tidy
          go test ./...

      - name: Publish to Go Proxy (on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          export GOPROXY=https://proxy.golang.org
          go list -m all  